"""Compaction and branch summarization for agent sessions.

Mechanical port of hoocode's ``packages/agent/src/harness/compaction/``.
"""

from __future__ import annotations

from .branch_summarization import (
    BranchPreparation,
    BranchSummaryDetails,
    BranchSummaryResult,
    CollectEntriesResult,
    collect_entries_for_branch_summary,
    generate_branch_summary_prompt,
    prepare_branch_entries,
)
from .compaction import (
    COMPACTION_SUMMARY_PREFIX,
    COMPACTION_SUMMARY_SUFFIX,
    DEFAULT_COMPACTION_SETTINGS,
    UPDATE_SUMMARIZATION_PROMPT,
    CompactionDetails,
    CompactionPreparation,
    CompactionResult,
    CompactionSettings,
    ContextUsageEstimate,
    CutPointResult,
    calculate_context_tokens,
    collect_messages_for_compaction,
    compact,
    compute_compaction_result,
    estimate_context_tokens,
    estimate_message_tokens,
    estimate_tokens,
    estimate_tokens_summary,
    extract_file_operations,
    find_cut_point,
    find_turn_start_index,
    find_valid_cut_points,
    generate_summary,
    generate_summary_prompt,
    generate_turn_prefix_summary,
    get_last_assistant_usage_from_entries,
    get_message_from_entry,
    prepare_compaction,
    should_compact,
)
from .utils import (
    SUMMARIZATION_SYSTEM_PROMPT,
    FileOperations,
    compute_file_lists,
    create_file_ops,
    extract_file_ops_from_message,
    format_file_operations,
    serialize_conversation,
)

__all__ = [
    # Compaction
    "CompactionResult",
    "CompactionDetails",
    "CompactionSettings",
    "CompactionPreparation",
    "ContextUsageEstimate",
    "CutPointResult",
    "DEFAULT_COMPACTION_SETTINGS",
    "COMPACTION_SUMMARY_PREFIX",
    "COMPACTION_SUMMARY_SUFFIX",
    "UPDATE_SUMMARIZATION_PROMPT",
    "estimate_tokens",
    "estimate_message_tokens",
    "estimate_tokens_summary",
    "calculate_context_tokens",
    "estimate_context_tokens",
    "collect_messages_for_compaction",
    "compute_compaction_result",
    "should_compact",
    "find_valid_cut_points",
    "find_turn_start_index",
    "find_cut_point",
    "extract_file_operations",
    "generate_summary",
    "generate_summary_prompt",
    "generate_turn_prefix_summary",
    "get_last_assistant_usage_from_entries",
    "get_message_from_entry",
    "prepare_compaction",
    "compact",
    "compute_file_lists",
    # Branch summarization
    "BranchSummaryResult",
    "BranchSummaryDetails",
    "BranchPreparation",
    "CollectEntriesResult",
    "collect_entries_for_branch_summary",
    "prepare_branch_entries",
    "generate_branch_summary_prompt",
    # Utils
    "FileOperations",
    "SUMMARIZATION_SYSTEM_PROMPT",
    "create_file_ops",
    "extract_file_ops_from_message",
    "format_file_operations",
    "serialize_conversation",
]
