#!/usr/bin/env python3
"""Convert TypeScript image models to Python format."""

import json
import re
import sys
from pathlib import Path


def parse_ts_image_models(ts_content: str) -> dict:
    """Parse TypeScript IMAGE_MODELS object to Python dict."""
    # Extract the IMAGE_MODELS object from TypeScript
    # Find the start of the object
    start_match = re.search(r"export const IMAGE_MODELS = \{", ts_content)
    if not start_match:
        raise ValueError("Could not find IMAGE_MODELS export")

    # Find the matching closing brace
    brace_count = 0
    start_idx = start_match.end() - 1  # Include the opening brace
    for i, char in enumerate(ts_content[start_idx:], start_idx):
        if char == "{":
            brace_count += 1
        elif char == "}":
            brace_count -= 1
            if brace_count == 0:
                end_idx = i + 1
                break
    else:
        raise ValueError("Could not find matching closing brace")

    ts_object = ts_content[start_idx:end_idx]

    # Convert TypeScript to JSON-like format
    # Remove 'satisfies' clauses
    ts_object = re.sub(r"\s*satisfies\s+[^,]+", "", ts_object)
    # Remove 'as const' clauses
    ts_object = re.sub(r"\s+as\s+const", "", ts_object)
    # Remove trailing commas before closing braces
    ts_object = re.sub(r",\s*}", "}", ts_object)
    # Remove trailing commas before closing brackets
    ts_object = re.sub(r",\s*]", "]", ts_object)
    # Quote unquoted keys (word characters before colon)
    ts_object = re.sub(r"(\{|,)\s*(\w+)\s*:", r'\1 "\2":', ts_object)
    # Convert TypeScript types to JSON
    ts_object = ts_object.replace("true", "true").replace("false", "false")

    # Parse as JSON
    try:
        return json.loads(ts_object)
    except json.JSONDecodeError as e:
        print(f"Error parsing JSON: {e}", file=sys.stderr)
        print(f"First 500 chars: {ts_object[:500]}", file=sys.stderr)
        raise


def convert_to_python_dict(ts_data: dict, indent: int = 0) -> str:
    """Convert TypeScript data to Python dict literal."""
    lines = []
    prefix = "    " * indent

    for key, value in ts_data.items():
        if isinstance(value, dict):
            # Check if this is a provider -> models mapping
            if any(isinstance(v, dict) and "id" in v for v in value.values()):
                # This is a provider with models
                lines.append(f"{prefix}{key!r}: {{")
                for model_id, model in value.items():
                    lines.append(f"{prefix}    {model_id!r}: {{")
                    for prop, prop_value in model.items():
                        if isinstance(prop_value, (dict, list)):
                            prop_str = json.dumps(prop_value, ensure_ascii=False)
                            lines.append(f"{prefix}        {prop!r}: {prop_str},")
                        else:
                            lines.append(f"{prefix}        {prop!r}: {prop_value!r},")
                    lines.append(f"{prefix}    }},")
                lines.append(f"{prefix}}},")
            else:
                # Regular nested dict
                lines.append(f"{prefix}{key!r}: {{")
                for prop, prop_value in value.items():
                    if isinstance(prop_value, (dict, list)):
                        prop_str = json.dumps(prop_value, ensure_ascii=False)
                        lines.append(f"{prefix}    {prop!r}: {prop_str},")
                    else:
                        lines.append(f"{prefix}    {prop!r}: {prop_value!r},")
                lines.append(f"{prefix}}},")
        elif isinstance(value, list):
            lines.append(f"{prefix}{key!r}: {json.dumps(value, ensure_ascii=False)},")
        else:
            lines.append(f"{prefix}{key!r}: {value!r},")

    return "\n".join(lines)


def main():
    ts_file = Path("/Users/sachinkoli/github/hoocode/packages/ai/src/image-models.generated.ts")
    py_file = Path(
        "/Users/sachinkoli/github/pycortex/packages/ai/models/src/cortex/ai/models/image_models_generated.py"
    )

    print(f"Reading {ts_file}...")
    ts_content = ts_file.read_text()

    print("Parsing TypeScript image models...")
    ts_data = parse_ts_image_models(ts_content)

    print("Converting to Python...")
    python_dict = convert_to_python_dict(ts_data)

    py_content = f'''"""Auto-generated image model data.

Port of hoocode's `packages/ai/src/image-models.generated.ts`.
This file was auto-generated by scripts/convert_image_models.py.
Do not edit manually - run the conversion script to update.
"""

# Image model data organized by provider
IMAGE_MODELS: dict[str, dict[str, dict]] = {{
{python_dict}
}}
'''

    print(f"Writing {py_file}...")
    py_file.parent.mkdir(parents=True, exist_ok=True)
    py_file.write_text(py_content)

    print("Done!")


if __name__ == "__main__":
    main()
