"""Configuration utilities for the Cortex code package."""

# Re-export config module
# Re-export auth guidance
from cortex.code.config.auth_guidance import (
    format_no_api_key_found_message,
    format_no_model_selected_message,
    format_no_models_available_message,
    get_provider_login_help,
)
from cortex.code.config.auth_storage import (
    ApiKeyCredential,
    AuthCredential,
    AuthStatus,
    AuthStorage,
    AuthStorageBackend,
    FileAuthStorageBackend,
    InMemoryAuthStorageBackend,
    LockResult,
    OAuthCredential,
)
from cortex.code.config.config import (
    APP_NAME,
    APP_TITLE,
    CONFIG_DIR_NAME,
    DISPATCH_DIR_NAME,
    ENV_AGENT_DIR,
    ENV_SESSION_DIR,
    VERSION,
    expand_tilde_path,
    get_agent_dir,
    get_auth_path,
    get_bin_dir,
    get_bundled_interactive_asset_path,
    get_changelog_path,
    get_custom_themes_dir,
    get_debug_log_path,
    get_dispatch_root,
    get_dispatch_task_dir,
    get_docs_path,
    get_examples_path,
    get_export_template_dir,
    get_hoo_code_dir,
    get_interactive_assets_dir,
    get_models_path,
    get_package_dir,
    get_package_json_path,
    get_prompts_dir,
    get_readme_path,
    get_self_update_command,
    get_self_update_unavailable_instruction,
    get_sessions_dir,
    get_settings_path,
    get_share_viewer_url,
    get_subagent_spawn_command,
    get_templates_dir,
    get_themes_dir,
    get_tools_dir,
    get_update_instruction,
    is_bun_binary,
    is_bun_runtime,
)
from cortex.code.config.model_registry import (
    ModelDefinitionInput,
    ModelRegistry,
    ProviderConfigInput,
    ResolvedRequestAuth,
    clear_api_key_cache,
)
from cortex.code.config.provider_display_names import BUILT_IN_PROVIDER_DISPLAY_NAMES
from cortex.code.config.resolve_config_value import (
    clear_config_value_cache,
    resolve_config_value,
    resolve_config_value_or_throw,
    resolve_config_value_uncached,
    resolve_headers,
    resolve_headers_or_throw,
)

# Re-export settings defaults
from cortex.code.config.settings_defaults import DEFAULT_SETTINGS

# Re-export settings manager
from cortex.code.config.settings_manager import SettingsManager

# Re-export settings storage
from cortex.code.config.settings_storage import (
    FileSettingsStorage,
    InMemorySettingsStorage,
    SettingsError,
    SettingsScope,
    SettingsStorage,
)

# Re-export settings types
from cortex.code.config.settings_types import (
    BranchSummarySettings,
    CompactionSettings,
    ContextGcSettings,
    ImageSettings,
    MarkdownSettings,
    ModelCategories,
    PackageSource,
    PackageSourceFilter,
    ProviderRetrySettings,
    RetrySettings,
    Settings,
    TerminalSettings,
    ThinkingBudgetsSettings,
    ToolOutputSettings,
    VoiceSettings,
    WarningSettings,
    WebtoolsSettings,
)

__all__ = [
    # Config constants
    "APP_NAME",
    "APP_TITLE",
    "CONFIG_DIR_NAME",
    "DISPATCH_DIR_NAME",
    "ENV_AGENT_DIR",
    "ENV_SESSION_DIR",
    "VERSION",
    "is_bun_binary",
    "is_bun_runtime",
    # Config functions
    "expand_tilde_path",
    "get_agent_dir",
    "get_auth_path",
    "get_bin_dir",
    "get_bundled_interactive_asset_path",
    "get_changelog_path",
    "get_custom_themes_dir",
    "get_debug_log_path",
    "get_dispatch_root",
    "get_dispatch_task_dir",
    "get_docs_path",
    "format_no_api_key_found_message",
    "format_no_model_selected_message",
    "format_no_models_available_message",
    "get_provider_login_help",
    "get_examples_path",
    "get_export_template_dir",
    "get_hoo_code_dir",
    "get_interactive_assets_dir",
    "get_models_path",
    "get_package_dir",
    "get_package_json_path",
    "get_prompts_dir",
    "get_readme_path",
    "get_self_update_command",
    "get_self_update_unavailable_instruction",
    "get_sessions_dir",
    "get_settings_path",
    "get_share_viewer_url",
    "get_subagent_spawn_command",
    "get_templates_dir",
    "get_themes_dir",
    "get_tools_dir",
    "get_update_instruction",
    # Settings types
    "BranchSummarySettings",
    "CompactionSettings",
    "ContextGcSettings",
    "ImageSettings",
    "MarkdownSettings",
    "ModelCategories",
    "PackageSource",
    "PackageSourceFilter",
    "ProviderRetrySettings",
    "RetrySettings",
    "Settings",
    "TerminalSettings",
    "ThinkingBudgetsSettings",
    "ToolOutputSettings",
    "VoiceSettings",
    "WarningSettings",
    "WebtoolsSettings",
    # Settings defaults
    "DEFAULT_SETTINGS",
    # Settings storage
    "FileSettingsStorage",
    "InMemorySettingsStorage",
    "SettingsError",
    "SettingsScope",
    "SettingsStorage",
    # Settings manager
    "SettingsManager",
    # Auth storage
    "ApiKeyCredential",
    "AuthCredential",
    "AuthStatus",
    "AuthStorage",
    "AuthStorageBackend",
    "FileAuthStorageBackend",
    "InMemoryAuthStorageBackend",
    "LockResult",
    "OAuthCredential",
    # Model registry
    "ModelDefinitionInput",
    "ModelRegistry",
    "ProviderConfigInput",
    "ResolvedRequestAuth",
    "clear_api_key_cache",
    # Provider display names
    "BUILT_IN_PROVIDER_DISPLAY_NAMES",
    # Config value resolution
    "clear_config_value_cache",
    "resolve_config_value",
    "resolve_config_value_or_throw",
    "resolve_config_value_uncached",
    "resolve_headers",
    "resolve_headers_or_throw",
]
